[package]
name = "freebox-exporter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.81"
clap = { version = "4.5.8", features = ["derive"] }
hmac = { version = "0.12.1", features = ["std"] }
prometheus_exporter = "0.8.5"
reqwest = { version = "0.12.5", features = ["json"] }
serde = {version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
sha1 = "0.10.6"
tokio = { version = "1.38.0", features = ["full"]}
toml = "0.8.14"
